# Azure Sentinel Configuration
# Update these values for your environment

sentinel:
  # Azure subscription details
  subscription_id: 00000000-0000-0000-0000-000000000000  # Your subscription ID
  resource_group: rg-security  # Resource group name
  workspace_name: law-sentinel  # Log Analytics workspace name

  # Authentication (uses DefaultAzureCredential)
  # Supports: Azure CLI, Managed Identity, Environment Variables, etc.
  # See: https://docs.microsoft.com/en-us/python/api/azure-identity/azure.identity.defaultazurecredential

  # Analytics rule settings
  analytics:
    query_frequency: PT15M  # Run every 15 minutes (ISO 8601 duration)
    query_period: PT15M     # Look back 15 minutes
    trigger_threshold: 0     # Alert on any results
    suppression_duration: PT1H  # Suppress duplicates for 1 hour

  # Incident creation settings
  incidents:
    create_incident: true
    grouping:
      enabled: false
      lookback_duration: PT5H
      matching_method: AllEntities  # AllEntities, AnyAlert, Selected

# Sigma rule conversion settings
sigma:
  rules_directory: ../../../detection-rules/sigma

  # Rule filtering (optional)
  filters:
    # Only deploy rules with these levels
    levels:
      - critical
      - high
      - medium

  # Rule customization
  customize:
    # Add custom KQL filters to all queries
    # additional_filter: "| where Computer startswith 'PROD-'"

# Logging
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR
  file: sentinel_deployment.log
