# Prometheus Alert Rules for Defensive Toolkit
# Security-focused alerts for API and infrastructure monitoring
# Version: 1.3.0

groups:
  # ============================================================================
  # API Health & Performance Alerts
  # ============================================================================
  - name: api_health
    interval: 30s
    rules:
      - alert: APIDown
        expr: up{job="defensive-toolkit-api"} == 0
        for: 1m
        labels:
          severity: critical
          component: api
        annotations:
          summary: "Defensive Toolkit API is down"
          description: "API has been unreachable for more than 1 minute"

      - alert: APIHighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          component: api
        annotations:
          summary: "High API error rate detected"
          description: "API error rate is {{ $value | humanizePercentage }} over the last 5 minutes"

      - alert: APISlowResponse
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          component: api
        annotations:
          summary: "API response time is slow"
          description: "95th percentile response time is {{ $value }}s"

  # ============================================================================
  # Security Alerts
  # ============================================================================
  - name: security
    interval: 30s
    rules:
      - alert: HighAuthenticationFailures
        expr: rate(auth_failures_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          component: security
        annotations:
          summary: "High authentication failure rate"
          description: "{{ $value }} failed authentication attempts per second"

      - alert: RateLimitExceeded
        expr: rate(rate_limit_exceeded_total[5m]) > 50
        for: 5m
        labels:
          severity: info
          component: security
        annotations:
          summary: "Rate limit frequently exceeded"
          description: "Rate limit exceeded {{ $value }} times per second"

      - alert: SuspiciousAPIActivity
        expr: rate(http_requests_total{path=~".*(admin|config|env|secret).*"}[5m]) > 5
        for: 2m
        labels:
          severity: warning
          component: security
        annotations:
          summary: "Suspicious API path access detected"
          description: "Unusual access to sensitive paths detected"

  # ============================================================================
  # Resource Utilization Alerts
  # ============================================================================
  - name: resources
    interval: 30s
    rules:
      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / 1024 / 1024 > 1024
        for: 5m
        labels:
          severity: warning
          component: api
        annotations:
          summary: "High memory usage"
          description: "API using {{ $value }}MB of memory"

      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
          component: api
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value | humanizePercentage }}"

  # ============================================================================
  # Prometheus System Alerts
  # ============================================================================
  - name: prometheus
    interval: 30s
    rules:
      - alert: PrometheusConfigReloadFailed
        expr: prometheus_config_last_reload_successful == 0
        for: 5m
        labels:
          severity: warning
          component: prometheus
        annotations:
          summary: "Prometheus configuration reload failed"
          description: "Prometheus configuration reload has failed"

      - alert: PrometheusTSDBCompactionsFailed
        expr: rate(prometheus_tsdb_compactions_failed_total[5m]) > 0
        for: 5m
        labels:
          severity: warning
          component: prometheus
        annotations:
          summary: "Prometheus TSDB compactions failing"
          description: "Prometheus TSDB compactions are failing"
