---
name: "Malware Containment Workflow"
description: "Automated malware detection and containment response"
version: "1.0"
author: "Defensive Toolkit"

variables:
  infected_host: ""
  malware_hash: ""
  process_name: ""
  c2_ip: ""

tasks:
  - name: "Log incident start"
    action: log
    parameters:
      message: "Starting malware containment for host: ${infected_host}"
      level: error

  - name: "Isolate infected host"
    action: log
    parameters:
      message: "CONTAINMENT: Isolating host ${infected_host} from network"
      level: error

  - name: "Block C2 communication"
    action: conditional
    parameters:
      condition: "c2_ip != ''"
      if_true:
        - name: "Block C2 IP"
          action: log
          parameters:
            message: "Blocking C2 IP: ${c2_ip}"
            level: error

  - name: "Terminate malicious process"
    action: conditional
    parameters:
      condition: "process_name != ''"
      if_true:
        - name: "Kill process"
          action: log
          parameters:
            message: "Terminating process: ${process_name}"
            level: warning

  - name: "Collect forensics"
    action: log
    parameters:
      message: "Collecting memory dump and forensic artifacts"
      level: info

  - name: "Scan with Trivy"
    action: log
    parameters:
      message: "Running container vulnerability scan"
      level: info

  - name: "Quarantine malware file"
    action: log
    parameters:
      message: "Quarantining malware hash: ${malware_hash}"
      level: warning

  - name: "Enrich threat intelligence"
    action: log
    parameters:
      message: "Enriching IOCs with threat intel"
      level: info

  - name: "Create high-priority ticket"
    action: log
    parameters:
      message: "Creating CRITICAL incident ticket"
      level: error

  - name: "Notify security team"
    action: log
    parameters:
      message: "URGENT: Malware outbreak detected - ${infected_host}"
      level: error

  - name: "Log completion"
    action: log
    parameters:
      message: "Malware containment workflow completed"
      level: info
